class GuiLabel:
    NICO_CHAT_TOGGLE = "NicoChat 기능 사용"
    SKIP_VIDEO = "동영상 스킵"
    DELETE_VIDEO = "동영상 삭제"
    PLAY_VIDEO = "동영상 재생"
    CREATE_BROWSER = "브라우저 소스 생성"
    REFRESH_BROWSER = "브라우저 소스 새로고침"
    DELETE_BROWSER = "브라우저 소스 삭제"
    UPDATE_VIDEO_LIST = "동영상 리스트 업데이트"
    CURRENT_VIDEO_INFO = "현재 재생 중인 동영상: {}/{}"
    VIDEO_INFO_NONE = "제목: 없음, 채널: 없음"
    REMAINING_TIME = "남은 시간: {}"
    ERROR_SKIP_VIDEO = "Failed to skip the current video: {}"
    ERROR_REFRESH_BROWSER = "Failed to refresh browser source: {}"
    ERROR_DELETE_BROWSER = "Failed to delete browser source: {}"
    ERROR_CREATE_BROWSER = "Failed to create browser source: {}"