class GuiCommand:
    NICO_CHAT_TOGGLE = "니코동 채팅 ON/OFF"
    VIDEO_REQUEST_TOGGLE = "!유튜브 ON/OFF"
    HELLO_TOGGLE = "!안녕 ON/OFF"
    SKIP_VIDEO = "동영상 스킵"
    DELETE_VIDEO = "동영상 삭제"
    PLAY_VIDEO = "동영상 재생"
    CREATE_BROWSER = "브라우저 소스 생성"
    REFRESH_BROWSER = "브라우저 소스 새로고침"
    DELETE_BROWSER = "브라우저 소스 삭제"